Adding stock and flow AMRs to data/models
DARPA-ASKEM/simulation-integration pull request #36
Opened 2023-11-27 17:52 UTC by sabinala

This PR will add the gold-star stock-and-flow example AMRs to `data/models`.

Closes #35

2023-11-27 18:13 UTC, fivegrant requested changes
This looks good. The only issue is that this breaks the seeding step since these models don't have unique identifiers. Once that's fixed, it should work.

2023-11-27 18:13 UTC, fivegrant commented on data/models/SEIRD_stockflow.json
> +{
```suggestion
{
  "id": "seird-stockflow",
```

2023-11-27 18:13 UTC, fivegrant commented on data/models/SEIRHDS_stockflow.json
> +{
```suggestion
{
  "id": "seirhds-stockflow",
```

2023-11-27 18:13 UTC, fivegrant commented on data/models/SEIRHD_stockflow.json
> +{
```suggestion
{
  "id": "seirhd-stockflow",
```

2023-11-27 18:13 UTC, fivegrant commented on data/models/SEIR_stockflow.json
> +{
```suggestion
{
  "id": "seir-stockflow",
```

2023-11-27 18:13 UTC, fivegrant commented on data/models/SIR_stockflow.json
> +{
```suggestion
{
  "id": "sir-stockflow",
```

2023-11-27 18:46 UTC, sabinala commented
Alright, I've added the unique model ids @fivegrant suggested. Should be good to go!

2023-11-28 16:21 UTC, fivegrant approved these changes
thanks!

2023-11-28 16:21 UTC, merged